### ISSUE TITLE
If browser is not chrome, trigger chrome download

### ISSUE THREAD

**Issue by pmaasz** [pmaasz/The-Anti-Social-Network#8]

**Comment by thirdecho** [comment]
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_useragent

**Comment by thirdecho** [comment]
https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B3AAFFD5D-DDD6-CEB1-6FDB-E65F63976421%7D%26lang%3Dde%26browser%3D3%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe

**Comment by pmaasz** [comment]
https://www.google.com/intl/de/chrome/
https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
